---
# roles/postgresql/tasks/main.yml
- name: Install PostgreSQL
  apt:
    name:
      - "postgresql-{{ postgresql_version }}"
      - "postgresql-contrib-{{ postgresql_version }}"
      - postgresql-client
      - python3-psycopg2
    state: present
    update_cache: yes

- name: Enable and start PostgreSQL service
  systemd:
    name: postgresql
    enabled: yes
    state: started

- name: Create PostgreSQL databases
  postgresql_db:
    name: "{{ item.name }}"
    state: present
  loop: "{{ postgresql_databases }}"
  become_user: postgres
  when: postgresql_databases is defined

- name: Create PostgreSQL users
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    state: present
  loop: "{{ postgresql_users }}"
  become_user: postgres
  when: postgresql_users is defined
