---
- name: Install Docker Compose v2 (plugin)
  ansible.builtin.apt:
    name: docker-compose-plugin
    state: present
    update_cache: yes

- name: Create Docker Compose directory
  ansible.builtin.file:
    path: /opt/docker-compose
    state: directory
    mode: '0755'

- name: Verify Docker Compose installation
  ansible.builtin.command: docker compose version
  register: compose_version
  changed_when: false

- name: Display Docker Compose version
  ansible.builtin.debug:
    var: compose_version.stdout
