---
# roles/influxdb/tasks/main.yml
- name: Add InfluxDB GPG key
  apt_key:
    url: https://repos.influxdata.com/influxdata-archive_compat.key
    state: present

- name: Add InfluxDB repository
  apt_repository:
    repo: "deb https://repos.influxdata.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: influxdb

- name: Install InfluxDB
  apt:
    name: influxdb2
    state: present
    update_cache: yes

- name: Enable and start InfluxDB service
  systemd:
    name: influxdb
    enabled: yes
    state: started
