---
# roles/consul/tasks/main.yml
- name: Add HashiCorp GPG key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add HashiCorp repository
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
    filename: hashicorp

- name: Install Consul
  apt:
    name: consul
    state: present
    update_cache: yes

- name: Enable and start Consul service
  systemd:
    name: consul
    enabled: yes
    state: started
