name: Auto Issue Generator
on:
  push:
    paths:
      - '**/*.py'
      - '**/*.js'
jobs:
  issue-creator:
    runs-on: ubuntu-latest
    steps:
      - name: Generate issues from changes
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const changedFiles = await github.rest.repos.getCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha
            });
            const files = changedFiles.data.files.map(f => f.filename).join(', ');
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `🤖 Review recent changes in: ${files}`,
              body: `AI review needed on: 
${files}`
            });
