name: Code Lint & Error Check
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout code
        uses: actions/checkout@v4
      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: 📦 Install dependencies
        run: |
          pip install flake8 black
      - name: 🔍 Run flake8 for errors
        run: |
          flake8 . --exclude venv --max-line-length=100
