name: Secrets Scan
on: [push, pull_request]
jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          scanArguments: '--regex --entropy=True .'
