name: Task Creator from TODOs
on:
  push:
    paths:
      - '**/*.py'
      - '**/*.js'
jobs:
  scan-todos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Find TODOs
        run: |
          grep -rnw './' -e 'TODO' | while read -r line ; do
            echo "Creating issue: $line"
            gh issue create --title "📝 Task: $line" --body "$line" || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
