---
# roles/vscode/tasks/main.yml
- name: Add Microsoft GPG key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add VS Code repository
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/code stable main"
    state: present
    filename: vscode

- name: Install VS Code
  apt:
    name: code
    state: present
    update_cache: yes

- name: Install VS Code extensions
  become: no
  command: "code --install-extension {{ item }}"
  loop: "{{ vscode_extensions }}"
  when: vscode_extensions is defined
  ignore_errors: yes
