---
# roles/kafka/tasks/main.yml
- name: Install Java (required for Kafka)
  apt:
    name: openjdk-11-jdk
    state: present

- name: Download Kafka
  get_url:
    url: "https://downloads.apache.org/kafka/{{ kafka_version }}/kafka_2.13-{{ kafka_version }}.tgz"
    dest: /tmp/kafka.tgz

- name: Extract Kafka
  unarchive:
    src: /tmp/kafka.tgz
    dest: /opt
    remote_src: yes

- name: Create Kafka symlink
  file:
    src: "/opt/kafka_2.13-{{ kafka_version }}"
    dest: /opt/kafka
    state: link

- name: Create Kafka systemd service
  copy:
    dest: /etc/systemd/system/kafka.service
    content: |
      [Unit]
      Description=Apache Kafka
      After=network.target

      [Service]
      Type=simple
      WorkingDirectory=/opt/kafka
      ExecStart=/opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target
  notify: reload systemd

- name: Enable and start Kafka service
  systemd:
    name: kafka
    enabled: yes
    state: started
