---
- name: Install Node.js prerequisites
  ansible.builtin.apt:
    name:
      - curl
      - gnupg
    state: present
    update_cache: yes

- name: Add NodeSource GPG key
  ansible.builtin.apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add NodeSource repository
  ansible.builtin.apt_repository:
    repo: "deb https://deb.nodesource.com/node_20.x {{ ansible_distribution_release }} main"
    state: present
    filename: nodesource

- name: Install Node.js
  ansible.builtin.apt:
    name: nodejs
    state: present
    update_cache: yes

- name: Create AnythingLLM directory
  ansible.builtin.file:
    path: /opt/anythingllm
    state: directory
    mode: '0755'

- name: Pull AnythingLLM Docker image
  community.docker.docker_image:
    name: mintplexlabs/anythingllm
    source: pull
    tag: latest

- name: Create AnythingLLM container
  community.docker.docker_container:
    name: anythingllm
    image: mintplexlabs/anythingllm:latest
    state: started
    restart_policy: always
    ports:
      - "3001:3001"
    volumes:
      - /opt/anythingllm:/app/server/storage
    env:
      STORAGE_DIR: "/app/server/storage"
