---
- name: Add ZeroTier GPG key
  ansible.builtin.apt_key:
    url: https://raw.githubusercontent.com/zerotier/ZeroTierOne/master/doc/contact%40zerotier.com.gpg
    state: present

- name: Add ZeroTier repository
  ansible.builtin.apt_repository:
    repo: "deb https://download.zerotier.com/debian/{{ ansible_distribution_release }} {{ ansible_distribution_release }} main"
    state: present
    filename: zerotier

- name: Install ZeroTier One
  ansible.builtin.apt:
    name: zerotier-one
    state: present
    update_cache: yes

- name: Enable and start ZeroTier service
  ansible.builtin.systemd:
    name: zerotier-one
    enabled: yes
    state: started

- name: Join ZeroTier network
  ansible.builtin.command: zerotier-cli join {{ zerotier_network_id }}
  when: zerotier_network_id is defined
  register: join_result
  changed_when: "'200 join OK' in join_result.stdout"
  ignore_errors: yes

- name: Get ZeroTier node ID
  ansible.builtin.command: zerotier-cli info
  register: zerotier_info
  changed_when: false

- name: Display ZeroTier info
  ansible.builtin.debug:
    var: zerotier_info.stdout
