---
# roles/docker-compose/tasks/main.yml
- name: Download Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Verify Docker Compose installation
  command: docker-compose --version
  register: docker_compose_check
  changed_when: false

- name: Display Docker Compose version
  debug:
    var: docker_compose_check.stdout
