---
- name: Create prometheus system group
  ansible.builtin.group:
    name: prometheus
    system: yes
    state: present

- name: Create prometheus system user
  ansible.builtin.user:
    name: prometheus
    system: yes
    shell: /usr/sbin/nologin
    group: prometheus
    createhome: no

- name: Create prometheus directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Download prometheus
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version | default('2.45.0') }}/prometheus-{{ prometheus_version | default('2.45.0') }}.linux-amd64.tar.gz"
    dest: /tmp/prometheus.tar.gz
    mode: '0644'

- name: Extract prometheus
  ansible.builtin.unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /tmp
    remote_src: yes
    creates: "/tmp/prometheus-{{ prometheus_version | default('2.45.0') }}.linux-amd64"

- name: Copy prometheus binaries
  ansible.builtin.copy:
    src: "/tmp/prometheus-{{ prometheus_version | default('2.45.0') }}.linux-amd64/{{ item }}"
    dest: /usr/local/bin/
    remote_src: yes
    mode: '0755'
    owner: prometheus
    group: prometheus
  loop:
    - prometheus
    - promtool

- name: Copy prometheus console files
  ansible.builtin.copy:
    src: "/tmp/prometheus-{{ prometheus_version | default('2.45.0') }}.linux-amd64/{{ item }}"
    dest: /etc/prometheus/
    remote_src: yes
    owner: prometheus
    group: prometheus
  loop:
    - consoles
    - console_libraries

- name: Create prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'
  notify: Restart prometheus

- name: Create prometheus systemd service
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    mode: '0644'
  notify: Reload systemd

- name: Enable and start prometheus service
  ansible.builtin.systemd:
    name: prometheus
    enabled: yes
    state: started
