---
# roles/loki/tasks/main.yml
- name: Download Loki
  get_url:
    url: "https://github.com/grafana/loki/releases/latest/download/loki-linux-amd64.zip"
    dest: /tmp/loki.zip

- name: Extract Loki
  unarchive:
    src: /tmp/loki.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: '0755'

- name: Create Loki directory
  file:
    path: /etc/loki
    state: directory

- name: Create Loki configuration
  copy:
    dest: /etc/loki/loki-config.yml
    content: |
      auth_enabled: false
      server:
        http_listen_port: {{ loki_port }}
      ingester:
        lifecycler:
          ring:
            kvstore:
              store: inmemory
            replication_factor: 1
      schema_config:
        configs:
          - from: 2020-10-24
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 24h
      storage_config:
        boltdb_shipper:
          active_index_directory: /tmp/loki/boltdb-shipper-active
          cache_location: /tmp/loki/boltdb-shipper-cache
          cache_ttl: 24h
          shared_store: filesystem
        filesystem:
          directory: /tmp/loki/chunks
      limits_config:
        reject_old_samples: true
        reject_old_samples_max_age: 168h

- name: Create Loki systemd service
  copy:
    dest: /etc/systemd/system/loki.service
    content: |
      [Unit]
      Description=Loki
      After=network.target

      [Service]
      Type=simple
      ExecStart=/usr/local/bin/loki-linux-amd64 -config.file=/etc/loki/loki-config.yml
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target
  notify: reload systemd

- name: Enable and start Loki service
  systemd:
    name: loki
    enabled: yes
    state: started
