---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create Nginx sites directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /var/www
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled

- name: Configure Nginx virtual hosts
  ansible.builtin.template:
    src: site.conf.j2
    dest: "/etc/nginx/sites-available/{{ item.name }}.conf"
    mode: '0644'
  loop: "{{ nginx_vhosts | default([]) }}"
  notify: Reload nginx

- name: Enable Nginx sites
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ item.name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ item.name }}.conf"
    state: link
  loop: "{{ nginx_vhosts | default([]) }}"
  notify: Reload nginx

- name: Remove default Nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload nginx
  when: nginx_remove_default | default(true)

- name: Configure Nginx main config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  notify: Reload nginx

- name: Test Nginx configuration
  ansible.builtin.command: nginx -t
  register: nginx_test
  changed_when: false

- name: Enable and start Nginx service
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    state: started

- name: Configure firewall for Nginx
  ansible.builtin.ufw:
    rule: allow
    name: "Nginx Full"
  when: configure_firewall | default(true)
