---
- name: Install OpenSSH server
  ansible.builtin.apt:
    name: openssh-server
    state: present
    update_cache: yes

- name: Configure SSH for bastion host
  ansible.builtin.template:
    src: sshd_config_bastion.j2
    dest: /etc/ssh/sshd_config.d/bastion.conf
    mode: '0644'
    validate: '/usr/sbin/sshd -t -f %s'
  notify: Restart SSH

- name: Create bastion users group
  ansible.builtin.group:
    name: bastion-users
    state: present

- name: Configure fail2ban for SSH
  ansible.builtin.apt:
    name: fail2ban
    state: present

- name: Enable fail2ban service
  ansible.builtin.systemd:
    name: fail2ban
    enabled: yes
    state: started

- name: Install and configure firewall rules
  ansible.builtin.ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Enable UFW
  ansible.builtin.ufw:
    state: enabled
